index:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    version: 'v1'
    route: swagger_index
    permanent: true
    
api:
  path: /api/
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    version: 'v1'
    route: swagger_index
    permanent: true
    